
server.port=8080


spring.datasource.url=jdbc:h2:mem:tareawebdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=cc5002
spring.datasource.password=programacionweb
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.hibernate.ddl-auto=create-drop 


spring.sql.init.mode=always

spring.sql.init.data-locations=classpath:data.sql