# CONFIGURACIÓN DEL SERVIDOR
server.port=8080

# CONFIGURACIÓN DE LA BASE DE DATOS H2 (en memoria)
spring.datasource.url=jdbc:h2:mem:tareawebdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=cc5002
spring.datasource.password=programacionweb
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# CONFIGURACIÓN DE JPA/HIBERNATE
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.hibernate.ddl-auto=create-drop 

# Y esta línea para cargar los datos
spring.sql.init.mode=always
# Le dice a Spring Boot que el script de datos se llama tabla_notas.sql
spring.sql.init.data-locations=classpath:data.sql